site_name: ChatGPT For Teachers
site_description: 'Resources for showing teachers how to use ChatGPT to generate curriculum.  All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/CoderDojoTC/chat-gpt-for-teachers'

# CoderDojo Microsite Standards from here down

edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  language: en
  name: material
  logo: img/code-savvy-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2 - takes too long to build - use a screen image for now
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - footnotes
  - codehilite

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
    - Intro: concepts/index.md
    - Ethics: concepts/ethics.md
    - Prompts: concepts/prompts.md
    - Tokens: concepts/tokens.md
    - Output Formats: concepts/output-formats.md
  - Sample Prompts:
    - Intro: prompts/index.md
    - Syllabus: prompts/01-syllabus.md
    - Code of Conduct: prompts/02-code-of-conduct.md
    - Concept Graph: prompts/08-concept-graph.md 
    - License: prompts/03-license.md
    - License Footer: prompts/04-license-footer.md
    - Mkdocs Config: prompts/05-mkdocs.md
    - Lessons: prompts/06-lessons.md
    - Sample Code: prompts/09-sample-code.md
    - Turtle Graphics: prompts/09a-turtle-graphics.md
    - HTML: prompts/10-html.md
    - SVG: prompts/11-svg.md
    - Debugging: prompts/12-debugging.md
    - Explaining Code: prompts/17-explaining-code.md
    - Designing Robots: prompts/18-designing-robots.md
    - Comparing Microcontrollers: prompts/18-comparing-microcontrollers.md
    - Charts and Plotting: prompts/13-charts.md
    - Tables: prompts/14-tables.md
    - Glossary: prompts/07-glossary.md
  - Tips and Tricks: tips-and-tricks.md
  - Advanced Topics:
    - Intro: advanced-topics/index.md
  - Slides: slides.md
  - Glossary: glossary.md
  - Markdown Summary: markdown-summary.md
  - References: references.md
  - Contacts: contacts.md


#extra_css:
#  - custom.css
# Lets put the Google Analytics in here
# extra_javascript:
#  - custom.js
